learning_mechanism:
  class_path: split.disco.losses.DenseContrastiveLoss
  init_args:
    temperature: 0.1
    same_img_weight: 1.0
    T: 100
    number_patch_or_single_view: 1
    minimum_dim_output: 2
    eps: 1e-12

uncertainty_computer:
  class_path: split.disco.uncertainty.CoClusterUncertainty
  init_args:
    prior_weight: 2.0
    chunk_size: null
    eps: 1e-8

uncertainty_weight:
  class_path: split.disco.uncertainty.UncertaintyWeightComputer
  init_args:
    T: 100
    method: exp
    compute_method: vectorized
    eps: 1e-8

contrastive_model:
  class_path: split.disco.models.ContrastiveModel
  init_args:
    feature_dim: 768
    projection_dim: 256
    num_views_minimum: 2
    single_view: 1

training:
  class_path: split.disco.train.Trainer
  init_args:
    epochs: 100
    batch_size: 64
    learning_rate: 0.001
    weight_decay: 0.0001


optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.001
    weight_decay: 0.0001

scheduler:
  class_path: torch.optim.lr_scheduler.CosineAnnealingLR
  init_args:
    T_max: 100